### ISSUE TITLE
[BUG] Fix typo in app tier terraform file

### ISSUE THREAD

**Issue by tungbq** [tungbq/aws-lab-with-terraform#109]
See https://github.com/tungbq/aws-lab-with-terraform/blob/1b34478b3722b4ad917be239a130ea67f6c573f4/workshop/aws-3-tier-web/app.tf#LL2C44-L2C54
Just replace "HelloWorld" by current tag name in https://github.com/tungbq/aws-lab-with-terraform/blob/1b34478b3722b4ad917be239a130ea67f6c573f4/workshop/aws-3-tier-web/app.tf#L14

**Comment by Harshal662** [comment]
I can do that

**Comment by tungbq** [comment]
> I can do that

Great! Assigned the task to you. Please go ahead @Harshal662
