### ISSUE TITLE
Improve naming convention in `serverless-basic-application/api-gateway.tf`

### ISSUE THREAD

**Issue by tungbq** [tungbq/aws-lab-with-terraform#172]
Update some vaiables in https://github.com/tungbq/aws-lab-with-terraform/blob/main/tutorial/serverless-basic-application/api-gateway.tf as follow (just find and replace):

- `"aws_api_gateway_resource" "resource" `-> `"aws_api_gateway_resource" "app_resource"`
- aws_api_gateway_resource.resource -> aws_api_gateway_resource.app_resource
- `"aws_api_gateway_integration" "integration"` -> `"aws_api_gateway_integration" "app_integration"`
- aws_api_gateway_integration.integration -> aws_api_gateway_integration.app_integration
- `"aws_api_gateway_method" "method " `-> `"aws_api_gateway_method" "app_method "`
- aws_api_gateway_method.method -> aws_api_gateway_method.app_method
- `"aws_api_gateway_deployment" "example"` -> `"aws_api_gateway_deployment" "app_deployment"`
- aws_api_gateway_deployment.example -> aws_api_gateway_deployment.app_deployment

**Comment by 1fn0t** [comment]
Hi @tungbq, can I be assigned this issue?

**Comment by tungbq** [comment]
Sure, go ahead @1fn0t
