### ISSUE TITLE
doc/focalboard: correct the `terraform apply` instruction

### ISSUE THREAD

**Issue by tungbq** [tungbq/aws-lab-with-terraform#225]
There has a bug in https://github.com/tungbq/aws-lab-with-terraform/blob/main/selfhosted/focalboard/simple-focalboard/README.md
- Deploy `terraform apply`. Check then confirm by typing `y`

Should be:
- Deploy `terraform apply`. Check then confirm by typing `yes`

**Comment by BreakingPitt** [comment]
Hi:

@tungbq there is a new pull request  #235 that fix the problem.

Best regards

**Comment by tungbq** [comment]
Nice! Thanks @BreakingPitt for your contribution!

**Comment by tungbq** [comment]
@all-contributors please add @BreakingPitt as code

**Comment by tungbq** [comment]
Thanks @BreakingPitt again for your awe some contribution on this repo!
If you find this repository helpful, kindly consider showing your appreciation by giving it a star ⭐ Thanks! 💖
