### ISSUE TITLE
Add tungbq as default CODEOWNERS

### ISSUE THREAD

**Issue by tungbq** [tungbq/aws-lab-with-terraform#25]
See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file
Task:
- [ ] Create new `CODEOWNERS` file
- [ ] Add `*    @tungbq ` to the newly created file
- [ ] Open the PR and waiting for merge
- [ ] Done! <3

**Comment by blacklovertech** [comment]
Done

**Comment by tungbq** [comment]
> Done

Thanks so much for your contribution @blacklovertech.
Could you please link your PR to this ticket? (In the PR description,  there has a `Closes: #XXX` template, we can change it to `Closes: #25`

**Comment by blacklovertech** [comment]
https://github.com/tungbq/aws-lab-with-terraform/pull/26#issue-1746027869

https://github.com/tungbq/aws-lab-with-terraform/pull/27#issue-1746030925

**Comment by tungbq** [comment]
Thanks @blacklovertech for y our work, if you interest on more contribution, you can work on the ticket in this list:
https://github.com/tungbq/aws-lab-with-terraform/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
