### ISSUE TITLE
Standarize README.md for install Terraform section

### ISSUE THREAD

**Issue by tungbq** [tungbq/aws-lab-with-terraform#53]
Add a bullet point to **How to install Terraform** section of README.md
Just replace `See: https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli
` by:
`- See: https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli
`

**Comment by Harshal662** [comment]
i can do that

**Comment by tungbq** [comment]
> i can do that

Sure, plz go ahead
