### ISSUE TITLE
Fix typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by tungbq** [tungbq/aws-lab-with-terraform#54]
Rename `devops-basic` word to `aws-lab-with-terraform`:
![image](https://github.com/tungbq/aws-lab-with-terraform/assets/85242618/fe1d9664-a47c-4ce4-907d-92c77089e13f)
Also it would be nice if we could check if there has any other typo like this in the CONTRIBUTING.md file. Thanks

**Comment by Harshal662** [comment]
i can do that

**Comment by tungbq** [comment]
> i can do that

Sure, plz go ahead
