### ISSUE TITLE
[ci] Skip running greetings.yml workflow on the PR created by all-contributors bot

### ISSUE THREAD

**Issue by tungbq** [tungbq/aws-lab-with-terraform#73]
In case the PR created by all-contributors bot, we should skip running this workflow:
https://github.com/tungbq/aws-lab-with-terraform/blob/main/.github/workflows/greetings.yml
For example: PR #70

**Comment by Harshal662** [comment]
I can do that

**Comment by tungbq** [comment]
> I can do that
> 
> 

Thanks, assigning it to you
