### ISSUE TITLE
[Part3] Create new shell script to automate App Tier Instance Deployment - Configure Database

### ISSUE THREAD

**Issue by tungbq** [tungbq/aws-lab-with-terraform#75]
Task:
- Create new folder name `script `under `workshop/aws-3-tier-web` (`workshop/aws-3-tier-web/script`)
- Create new script name `configure_database.sh` under `workshop/aws-3-tier-web/script`
- Read this Configure Database page: https://catalog.us-east-1.prod.workshops.aws/workshops/85cd2bb2-7f79-4e96-bdee-8078e469752a/en-US/part3/configuredatabase
- Add all the shell commmands from the [Configure Database page](https://catalog.us-east-1.prod.workshops.aws/workshops/85cd2bb2-7f79-4e96-bdee-8078e469752a/en-US/part3/configuredatabase) to `configure_database.sh`
- Create the PR and waiting for review
- Done!

Note that this script will be used in the terraform file for the deployment.

**Comment by Harshal662** [comment]
I can do that

**Comment by tungbq** [comment]
> I can do that

Great! Assigned the task to you. Please go ahead @Harshal662

**Comment by Harshal662** [comment]
mysql -h CHANGE-TO-YOUR-RDS-ENDPOINT -u CHANGE-TO-USER-NAME -p

should I leave as it is or there are specific name I have to give?

**Comment by tungbq** [comment]
> mysql -h CHANGE-TO-YOUR-RDS-ENDPOINT -u CHANGE-TO-USER-NAME -p
> 
> should I leave as it is or there are specific name I have to give?

Good question @Harshal662, please create 2 variables for this input, add a placeholder to these variables value (I will update it later). Then use the variable for the mysql command.
