### ISSUE TITLE
Remove unused comment in workshop/aws-3-tier-web/networking.tf

### ISSUE THREAD

**Issue by tungbq** [tungbq/aws-lab-with-terraform#90]
Remove all the `  # Replace with your desired availability zone` text out of https://github.com/tungbq/aws-lab-with-terraform/blob/main/workshop/aws-3-tier-web/networking.tf as it's added by typo.
For example:
https://github.com/tungbq/aws-lab-with-terraform/blob/349e07414b0a40c3e6c728568f4448d47660c97e/workshop/aws-3-tier-web/networking.tf#L11

**Comment by navyanihitha** [comment]
Hi @tungbq , Wanted to check if I can work on this issue and can be assigned to me.

**Comment by tungbq** [comment]
> Hi @tungbq , Wanted to check if I can work on this issue and can be assigned to me.

Sure @navyanihitha, please go ahead

**Comment by tungbq** [comment]
@all-contributors please add @navyanihitha as code
